### ISSUE TITLE
Failed to run on Mojave

### ISSUE THREAD

**Issue by laurent-d** [brainly/html-sketchapp-example#2]
Hi,
Thankq for your robust works !
I tried to run your script after building it but i have some issues about chromium.
Any ideas about how to resolve it ?

Attached the Terminal message : 

MacBook-Pro-de-Laurent:html-sketchapp-example xxx$ npm run inject http://sketchapp.com

> html-sketchapp-example@1.0.0 inject /Users/xxx/html-sketchapp-example
> node ./src/inject.js "http://sketchapp.com"

Assertion failed: Chromium revision is not downloaded. Run "npm install"
(node:708) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! spawn /Users/xxx/html-sketchapp-example/node_modules/puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/MacOS/Chromium ENOENT

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/xxx/html-sketchapp-example/node_modules/puppeteer/lib/Launcher.js:211:14)
    at ChildProcess.helper.addEventListener.error (/Users/xxx/html-sketchapp-example/node_modules/puppeteer/lib/Launcher.js:202:64)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My OSX version is Mojave and the NodeJs one is 10.10 but i tried the last Lts add have the same issue.

**Comment by LincMitch** [comment]
I had a similar issue with HTML Sketchapp CLI and in the config file I needed to rem out:
// puppeteerArgs: '--no-sandbox --disable-setuid-sandbox',
// puppeteerExecutablePath: 'google-chrome-unstable'

Not sure if this will help you and sorry I can't help more.

**Comment by kdzwinel** [comment]
Since this was reported we have upgraded bunch of things (including puppeteer), so everything should work smoothly. Feel free to reopen if issue persists.
