### ISSUE TITLE
Mocked Data haha

### ISSUE THREAD

**Issue by zmnv** [brainly/html-sketchapp-example#3]
![image](https://user-images.githubusercontent.com/25253501/51965629-af88ff80-249c-11e9-9199-bc989146b9fc.png)

Why?....

![image](https://user-images.githubusercontent.com/25253501/51967033-d47f7180-24a0-11e9-9af0-f6234b26b882.png)

why?....

html-sketchapp-example was clear, and ready-to-go. 

Now you should dance with drums for just run it...

**Comment by MaxPMagee** [comment]
Hey guys- any idea why the url supplied is ignored and hardcoded to login as @burakukula ? Last update says update version numbers, but now it overwrites any input and injects (Polish) test data? I'm not a Polish speaker, so I can't tell 100% if this is accidental or intentional. @kdzwinel , could you at least update the readme for the example to indicate that this is intentional?

@zmnv, which drums do I need to run it? :-)

**Comment by zmnv** [comment]
@MaxPMagee 

just change **inject.js** to clear:

```js
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const {URL} = require('url');

const url = process.argv[2]; // uncomment this
const outputFile = '../page.asketch.json';

puppeteer.launch({headless: false}).then(async browser => {
  const page = await browser.newPage();

  await page.setViewport({width: 1480, height: 1803});
  await page.goto(new URL(url)); // url by command line
  await page.waitFor(3000);

  await page.addScriptTag({
    path: './dist/build/page2layers.bundle.js' // <- Change This
  });

  // JSON.parse + JSON.stringify hack is only needed until
  // https://github.com/GoogleChrome/puppeteer/issues/1510 is fixed
  const asketchPageJSONString = await page.evaluate(
    'JSON.stringify(page2layers.run())'
  );

  fs.writeFileSync(path.resolve(__dirname, outputFile), asketchPageJSONString);
  browser.close();
});
```

**Comment by MaxPMagee** [comment]
@zmnv I'm still not hearing any drums. ;-) 🥁 Thanks for your reply, I am aware that I can fix the example (and have), but my purpose was to tag the devs who maintain this repo and call their attention to an obviously broken public repo (cited in several popular projects, and this is pretty neat) that needs some love.

**Comment by burakukula** [comment]
@zmnv @MaxPMagee hey! Thx for reporting, it's totally my fault. shame on me. 😕
anyway. I just pushed changes and `inject.js` is clear now. I am closing the issue and I promise it's not gonna happen again 😉

I am closing the issue.
